// Generated by delombok at Thu Nov 04 20:42:18 PDT 2010
package pl.java.jc5.lombok.tostring;

public class Car extends Vehicle {
	private String producer;
	
	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public java.lang.String toString() {
		return "Car(super=" + super.toString() + ")";
	}
}