// Generated by delombok at Thu Nov 04 20:42:18 PDT 2010
package pl.java.jc5.lombok.synchronizedd;

public class Hashtable {
	/**
	 * The total number of entries in the hash table.
	 */
	private transient int count;
	
	public synchronized boolean isEmpty() {
		return count == 0;
	}
	
	public boolean isEmptyPlusPlus() {
		synchronized (this.$lock) {
			return count == 0;
		}
	}
	@java.lang.SuppressWarnings("all")
	private final java.lang.Object $lock = new java.lang.Object[0];
}