// Generated by delombok at Thu Nov 04 20:42:18 PDT 2010
package pl.java.jc5.lombok.data;

import java.util.Date;

public class Person {
	private String firstName;
	private String lastName;
	private Sex sex;
	private final Date birthDate;
	
	@java.beans.ConstructorProperties({"birthDate"})
	@java.lang.SuppressWarnings("all")
	public Person(final Date birthDate) {
		this.birthDate = birthDate;
	}
	
	@java.lang.SuppressWarnings("all")
	public String getFirstName() {
		return this.firstName;
	}
	
	@java.lang.SuppressWarnings("all")
	public String getLastName() {
		return this.lastName;
	}
	
	@java.lang.SuppressWarnings("all")
	public Sex getSex() {
		return this.sex;
	}
	
	@java.lang.SuppressWarnings("all")
	public Date getBirthDate() {
		return this.birthDate;
	}
	
	@java.lang.SuppressWarnings("all")
	public void setFirstName(final String firstName) {
		this.firstName = firstName;
	}
	
	@java.lang.SuppressWarnings("all")
	public void setLastName(final String lastName) {
		this.lastName = lastName;
	}
	
	@java.lang.SuppressWarnings("all")
	public void setSex(final Sex sex) {
		this.sex = sex;
	}
	
	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (o == null) return false;
		if (o.getClass() != this.getClass()) return false;
		final Person other = (Person)o;
		if (this.getFirstName() == null ? other.getFirstName() != null : !this.getFirstName().equals(other.getFirstName())) return false;
		if (this.getLastName() == null ? other.getLastName() != null : !this.getLastName().equals(other.getLastName())) return false;
		if (this.getSex() == null ? other.getSex() != null : !this.getSex().equals(other.getSex())) return false;
		if (this.getBirthDate() == null ? other.getBirthDate() != null : !this.getBirthDate().equals(other.getBirthDate())) return false;
		return true;
	}
	
	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public int hashCode() {
		final int PRIME = 31;
		int result = 1;
		result = result * PRIME + (this.getFirstName() == null ? 0 : this.getFirstName().hashCode());
		result = result * PRIME + (this.getLastName() == null ? 0 : this.getLastName().hashCode());
		result = result * PRIME + (this.getSex() == null ? 0 : this.getSex().hashCode());
		result = result * PRIME + (this.getBirthDate() == null ? 0 : this.getBirthDate().hashCode());
		return result;
	}
	
	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public java.lang.String toString() {
		return "Person(firstName=" + this.getFirstName() + ", lastName=" + this.getLastName() + ", sex=" + this.getSex() + ", birthDate=" + this.getBirthDate() + ")";
	}
}