// Generated by delombok at Thu Nov 04 20:42:18 PDT 2010
package pl.java.jc5.lombok.equalshashcode;

import lombok.EqualsAndHashCode;
import lombok.NonNull;

public class Person {
	private String firstName;
	@NonNull
	private String lastName;
	
	@java.lang.SuppressWarnings("all")
	private Person(@NonNull final String lastName) {
		if (lastName == null) throw new java.lang.NullPointerException("lastName");
		this.lastName = lastName;
	}
	
	@java.lang.SuppressWarnings("all")
	public static Person newInstance(@NonNull final String lastName) {
		return new Person(lastName);
	}
	
	@java.lang.SuppressWarnings("all")
	public String getFirstName() {
		return this.firstName;
	}
	
	@NonNull
	@java.lang.SuppressWarnings("all")
	public String getLastName() {
		return this.lastName;
	}
	
	@java.lang.SuppressWarnings("all")
	public void setFirstName(final String firstName) {
		this.firstName = firstName;
	}
	
	@java.lang.SuppressWarnings("all")
	public void setLastName(@NonNull final String lastName) {
		if (lastName == null) throw new java.lang.NullPointerException("lastName");
		this.lastName = lastName;
	}
	
	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (o == null) return false;
		if (o.getClass() != this.getClass()) return false;
		final Person other = (Person)o;
		if (this.getFirstName() == null ? other.getFirstName() != null : !this.getFirstName().equals(other.getFirstName())) return false;
		if (this.getLastName() == null ? other.getLastName() != null : !this.getLastName().equals(other.getLastName())) return false;
		return true;
	}
	
	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public int hashCode() {
		final int PRIME = 31;
		int result = 1;
		result = result * PRIME + (this.getFirstName() == null ? 0 : this.getFirstName().hashCode());
		result = result * PRIME + (this.getLastName() == null ? 0 : this.getLastName().hashCode());
		return result;
	}
	
	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public java.lang.String toString() {
		return "Person(firstName=" + this.getFirstName() + ", lastName=" + this.getLastName() + ")";
	}
}