// Generated by delombok at Thu Nov 04 20:42:18 PDT 2010
package pl.java.jc5.lombok.data.staticconstr;

import lombok.Data;
import lombok.Getter;
import lombok.NonNull;
import lombok.Setter;

public class Person {
	private String firstName;
	@NonNull
	private String lastName;
	
	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (o == null) return false;
		if (o.getClass() != this.getClass()) return false;
		final Person other = (Person)o;
		if (this.firstName == null ? other.firstName != null : !this.firstName.equals(other.firstName)) return false;
		if (this.lastName == null ? other.lastName != null : !this.lastName.equals(other.lastName)) return false;
		return true;
	}
	
	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public int hashCode() {
		final int PRIME = 31;
		int result = 1;
		result = result * PRIME + (this.firstName == null ? 0 : this.firstName.hashCode());
		result = result * PRIME + (this.lastName == null ? 0 : this.lastName.hashCode());
		return result;
	}
}