// Generated by delombok at Thu Nov 04 20:42:18 PDT 2010
package pl.java.jc5.lombok.sneakythrows;

import java.io.ByteArrayOutputStream;
import java.io.IOException;

public class CleanupAndSneakyThrowsTest {
	
	public void testCleanUp() {
		try {
			ByteArrayOutputStream baos = new ByteArrayOutputStream();
			try {
				baos.write(new byte[]{'Y', 'e', 's'});
				System.out.println(baos.toString());
			} finally {
				baos.close();
			}
		} catch (final java.lang.Throwable $ex) {
			throw lombok.Lombok.sneakyThrow($ex);
		}
	}
}