// Generated by delombok at Thu Nov 04 19:52:08 PDT 2010
package pl.java.jc5.lombok.sneakythrows;

import java.io.ByteArrayOutputStream;
import java.io.IOException;

public class CleanupTest {
	
	public void testCleanUp() {
		try {
			ByteArrayOutputStream baos = new ByteArrayOutputStream();
			try {
				baos.write(new byte[]{'Y', 'e', 's'});
				System.out.println(baos.toString());
			} finally {
				baos.close();
			}
		} catch (IOException e) {
			e.printStackTrace();
		}
	}
}