// Generated by delombok at Thu Nov 04 20:42:18 PDT 2010
package pl.java.jc5.lombok.cleanup;

import java.io.ByteArrayOutputStream;
import java.io.IOException;

public class CleanupTest {
	
	public void testCleanUp() throws IOException {
		ByteArrayOutputStream baos = new ByteArrayOutputStream();
		try {
			baos.write(new byte[]{'Y', 'e', 's'});
			System.out.println(baos.toString());
		} finally {
			baos.close();
		}
	}
}