// Generated by delombok at Thu Nov 04 20:42:18 PDT 2010
package pl.java.jc5.lombok.getter;

import java.util.Date;
import lombok.Data;

public class Person {
	private String firstName;
	private boolean employed = true;
	
	@java.lang.SuppressWarnings("all")
	public String getFirstName() {
		return this.firstName;
	}
	
	@java.lang.SuppressWarnings("all")
	public void setFirstName(final String firstName) {
		this.firstName = firstName;
	}
	
	@java.lang.SuppressWarnings("all")
	public boolean isEmployed() {
		return this.employed;
	}
	
	@java.lang.SuppressWarnings("all")
	protected void setEmployed(final boolean employed) {
		this.employed = employed;
	}
}