// Generated by delombok at Thu Nov 04 20:42:18 PDT 2010
package pl.java.jc5.lombok.nonnull;

import java.util.Date;
import lombok.Data;
import lombok.NonNull;

public class Person {
	@NonNull
	private String firstName;
	
	@NonNull
	@java.lang.SuppressWarnings("all")
	public String getFirstName() {
		return this.firstName;
	}
	
	@java.lang.SuppressWarnings("all")
	public void setFirstName(@NonNull final String firstName) {
		if (firstName == null) throw new java.lang.NullPointerException("firstName");
		this.firstName = firstName;
	}
}